backend:
  name: git-gateway
  branch: main
  media_folder: "_site/img" # Media files will be stored in the repo under static/images/uploads
  public_folder: "blog" 
  collections:
    - name: "blog" # Used in routes, e.g., /admin/collections/blog
      label: "Blog" # Used in the UI
      folder: "blog"
      create: true
      slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
      fields: 
        - {" label: 'Title', name: 'title', widget: 'string' "}
        - {" label: 'Description', name: 'description', widget: 'string' "}
        - {" label: 'Author', name: 'author', widget: 'string' "}
        - {" label: 'Date', name: 'date', widget: 'datetime' "}
        - {" label: 'Body', name: 'body', widget: 'markdown' "}